# Generated by Django 4.2.11 on 2026-05-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.facultad')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id_invitado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('motivo_visita', models.CharField(max_length=300)),
                ('fecha_visita', models.DateField()),
                ('expira_en', models.DateTimeField()),
                ('ya_ingreso', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('facultad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.facultad')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitados_registrados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
            },
        ),
        migrations.CreateModel(
            name='QrToken',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=500, unique=True)),
                ('tipo_persona', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('personal_externo', 'Personal Externo'), ('invitado', 'Invitado')], max_length=30)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('ip_generacion', models.CharField(blank=True, max_length=45, null=True)),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accesos.invitado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'QR token',
                'verbose_name_plural': 'QR tokens',
            },
        ),
        migrations.CreateModel(
            name='PersonaFacultad',
            fields=[
                ('id_persona_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vinculo', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('personal_externo', 'Personal Externo')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('desde', models.DateField(auto_now_add=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.facultad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Persona facultad',
                'verbose_name_plural': 'Personas facultad',
            },
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id_guardia', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accesos.ingreso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Guardia',
                'verbose_name_plural': 'Guardias',
            },
        ),
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('personal_externo', 'Personal Externo'), ('invitado', 'Invitado')], max_length=30)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('sede_pertenece', models.CharField(blank=True, max_length=150, null=True)),
                ('facultad_pertenece', models.CharField(blank=True, max_length=200, null=True)),
                ('carrera_pertenece', models.CharField(blank=True, max_length=200, null=True)),
                ('acceso_permitido', models.BooleanField(default=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accesos.guardia')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accesos.ingreso')),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accesos.invitado')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accesos.qrtoken')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Registro ingreso',
                'verbose_name_plural': 'Registros ingreso',
                'index_together': {('fecha_hora',), ('ingreso', 'fecha_hora'), ('usuario', 'fecha_hora')},
            },
        ),
        migrations.AddConstraint(
            model_name='qrtoken',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('usuario__isnull', False), ('invitado__isnull', True)), models.Q(('usuario__isnull', True), ('invitado__isnull', False)), _connector='OR'), name='chk_qr_token_usuario_xor_invitado'),
        ),
        migrations.AlterIndexTogether(
            name='qrtoken',
            index_together={('token_hash',), ('expira_en', 'usado')},
        ),
        migrations.AlterUniqueTogether(
            name='personafacultad',
            unique_together={('usuario', 'facultad', 'carrera', 'tipo_vinculo')},
        ),
        migrations.AlterIndexTogether(
            name='invitado',
            index_together={('fecha_visita', 'activo')},
        ),
    ]
