# Generated by Django 4.2.11 on 2026-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_personafacultad_paralelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafacultad',
            name='modalidad_ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personafacultad',
            name='periodo_ingreso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='turno',
            field=models.CharField(choices=[('jornada', 'Jornada 07:00 - 22:00'), ('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20),
        ),
    ]
