# Generated by Django 4.2.11 on 2026-05-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaExterna',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contrato_vigente', models.BooleanField(default=True)),
                ('contrato_desde', models.DateField(blank=True, null=True)),
                ('contrato_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa externa',
                'verbose_name_plural': 'Empresas externas',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('es_integral', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo'), ('guardia', 'Guardia'), ('personal_externo', 'Personal Externo')], max_length=30)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=15, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('foto_url', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'index_together': {('tipo_usuario', 'activo'), ('ci',)},
            },
        ),
        migrations.CreateModel(
            name='PersonalExterno',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empresaexterna')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Personal externo',
                'verbose_name_plural': 'Personal externo',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.sede')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_docente', models.CharField(max_length=30, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('duracion_anios', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_administrativo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_admin', models.CharField(max_length=30, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Administrativo',
                'verbose_name_plural': 'Administrativos',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Rol permiso',
                'verbose_name_plural': 'Roles permisos',
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nro_registro', models.CharField(max_length=30, unique=True)),
                ('modalidad_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo_ingreso', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True)),
                ('titulo_bachiller', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('departamento_origen', models.CharField(blank=True, max_length=80, null=True)),
                ('provincia_origen', models.CharField(blank=True, max_length=80, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'index_together': {('nro_registro',)},
            },
        ),
    ]
