# Generated by Django 4.2.11 on 2026-06-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_administrativo_nivel_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacionDTIC',
            fields=[
                ('id_sync', models.AutoField(primary_key=True, serialize=False)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('parcial', 'Parcial (con errores)'), ('fallido', 'Fallido'), ('simulado', 'Simulado (sin API real)')], default='exitoso', max_length=20)),
                ('usuarios_creados', models.IntegerField(default=0)),
                ('usuarios_actualizados', models.IntegerField(default=0)),
                ('usuarios_omitidos', models.IntegerField(default=0)),
                ('errores_count', models.IntegerField(default=0)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('api_url_usada', models.CharField(blank=True, max_length=500, null=True)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Sincronización DTIC',
                'verbose_name_plural': 'Sincronizaciones DTIC',
                'ordering': ['-iniciado_en'],
            },
        ),
    ]
